version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        ports:
        - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
        - mongo_data:/data/db

    postgres:
        image: postgres:16.3
        ports:
            - 29231:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready -U $${PG_USER} -d $${PG_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3.10.7-management
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
volumes:
    mongo_data:
    pg_data:
    rabbitmq:
